import 'dotenv/config';
import { createPrismaClient } from './prisma.factory';

const { prisma, disconnect } = createPrismaClient();

async function main() {
  await prisma.draftListing.createMany({
    data: [
      {
        hostId: '92fd022e-e347-4062-bc53-92b40fcac60e',
        propertyType: 'HOUSE',
        privacyType: 'ENTIRE',
        location: {
          lat: -34.603716,
          lng: -58.381579,
          city: 'Buenos Aires',
          state: 'Autonomous City of Buenos Aires',
          street: 'Corrientes Av.',
          country: 'Argentina',
          postcode: 'CF 1871',
          timezone: 'America/Argentina/Buenos_Aires',
          formatted:
            'Corrientes Av. 1051, San Nicolas, 1871 Buenos Aires, Argentina',
          housenumber: '1051',
        },
        checkInTime: '15:00',
        checkOutTime: '11:00',
        title: '',
        description: '',
        nightPrice: 0.0,
        promotions: [],
        beds: 0,
        maxGuests: 1,
        bedrooms: 0,
        bathrooms: 1,
        maxPets: 0,
        maxAdults: 2,
        maxInfants: 0,
        maxChildren: 0,
        amenities: [],
        images: [],
        minCancelDays: 3,
        currentStep: 6,
        visitedSteps: [0, 2, 6, 7],
      },
      {
        hostId: '1d7e3aeb-e7ee-44ec-8b85-30411ff5c070',
        propertyType: 'HOUSE',
        privacyType: 'ENTIRE',
        location: {
          lat: 0,
          lng: 0,
          city: '',
          state: '',
          street: '',
          country: '',
          postcode: '',
          timezone: '',
          formatted: '',
          housenumber: '',
        },
        checkInTime: '15:00',
        checkOutTime: '11:00',
        title: '',
        description: '',
        nightPrice: 0.0,
        promotions: [],
        beds: 0,
        maxGuests: 1,
        bedrooms: 0,
        bathrooms: 1,
        maxPets: 0,
        maxAdults: 2,
        maxInfants: 0,
        maxChildren: 0,
        amenities: [],
        images: [],
        minCancelDays: 3,
        currentStep: 0,
        visitedSteps: [],
      },
      {
        hostId: 'c06c2b71-2a7a-47bb-bca3-593a194b86f3',
        propertyType: 'HOUSE',
        privacyType: 'ENTIRE',
        location: {
          lat: 0,
          lng: 0,
          city: '',
          state: '',
          street: '',
          country: '',
          postcode: '',
          timezone: '',
          formatted: '',
          housenumber: '',
        },
        checkInTime: '15:00',
        checkOutTime: '11:00',
        title: '',
        description: '',
        nightPrice: 0.0,
        promotions: [],
        beds: 0,
        maxGuests: 1,
        bedrooms: 0,
        bathrooms: 1,
        maxPets: 0,
        maxAdults: 2,
        maxInfants: 0,
        maxChildren: 0,
        amenities: [],
        images: [],
        minCancelDays: 3,
        currentStep: 0,
        visitedSteps: [0],
      },
      {
        hostId: 'dbea12f9-5837-4f9f-928f-83d090793b44',
        propertyType: 'APARTMENT',
        privacyType: 'PRIVATE',
        location: {
          lat: 0,
          lng: 0,
          city: '',
          state: '',
          street: '',
          country: '',
          postcode: '',
          timezone: '',
          formatted: '',
          housenumber: '',
        },
        checkInTime: '15:00',
        checkOutTime: '11:00',
        title: '',
        description: '',
        nightPrice: 0.0,
        promotions: [],
        beds: 0,
        maxGuests: 1,
        bedrooms: 0,
        bathrooms: 1,
        maxPets: 0,
        maxAdults: 2,
        maxInfants: 0,
        maxChildren: 0,
        amenities: [],
        images: [],
        minCancelDays: 3,
        currentStep: 2,
        visitedSteps: [0, 1],
      },
      {
        hostId: 'dbea12f9-5837-4f9f-928f-83d090793b44',
        propertyType: 'CABIN',
        privacyType: 'ENTIRE',
        location: {
          lat: -34.590681,
          lng: -58.401528,
          city: 'Buenos Aires',
          state: 'Autonomous City of Buenos Aires',
          street: 'Anchorena, Tomas Manuel De, Dr.',
          country: 'Argentina',
          postcode: 'CF C1119ACO',
          timezone: 'America/Argentina/Buenos_Aires',
          formatted:
            '1753, Anchorena, Tomas Manuel De, Dr., Buenos Aires, Autonomous City of Buenos Aires, CF C1119ACO, Argentina',
          housenumber: '1753',
        },
        checkInTime: '15:00',
        checkOutTime: '11:00',
        title: '',
        description: '',
        nightPrice: 150.0,
        promotions: [
          {
            minNights: 9,
            description: '10% discount for 9 nights or more',
            discountPercentage: 10,
          },
          {
            minNights: 7,
            description: '4% discount for 7 nights or more',
            discountPercentage: 4,
          },
        ],
        beds: 4,
        maxGuests: 4,
        bedrooms: 2,
        bathrooms: 1,
        maxPets: 1,
        maxAdults: 4,
        maxInfants: 1,
        maxChildren: 2,
        amenities: [],
        images: [],
        minCancelDays: 7,
        currentStep: 11,
        visitedSteps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        hostId: '3eb7caec-dac3-40fb-923c-31d2424e7a0e',
        propertyType: 'HOUSE',
        privacyType: 'ENTIRE',
        location: {
          lat: 0,
          lng: 0,
          city: '',
          state: '',
          street: '',
          country: '',
          postcode: '',
          timezone: '',
          formatted: '',
          housenumber: '',
        },
        checkInTime: '15:00',
        checkOutTime: '11:00',
        title: '',
        description: '',
        nightPrice: 0.0,
        promotions: [],
        beds: 0,
        maxGuests: 1,
        bedrooms: 0,
        bathrooms: 1,
        maxPets: 0,
        maxAdults: 2,
        maxInfants: 0,
        maxChildren: 0,
        amenities: [],
        images: [],
        minCancelDays: 3,
        currentStep: 2,
        visitedSteps: [0],
      },
      {
        hostId: 'dbea12f9-5837-4f9f-928f-83d090793b44',
        propertyType: 'APARTMENT',
        privacyType: 'PRIVATE',
        location: {
          lat: -38.7056784,
          lng: -62.2712184,
          city: 'Bahía Blanca',
          state: 'Buenos Aires',
          street: 'Zapiola',
          country: 'Argentina',
          postcode: 'B 8000',
          timezone: 'America/Argentina/Buenos_Aires',
          formatted:
            '957, Zapiola, Bahía Blanca, Buenos Aires, B 8000, Argentina',
          housenumber: '957',
        },
        checkInTime: '15:00',
        checkOutTime: '11:00',
        title: 'blabla',
        description: '',
        nightPrice: 103.0,
        promotions: [
          {
            minNights: 3,
            description: '10% discount for 3 nights or more',
            discountPercentage: 10,
          },
        ],
        beds: 0,
        maxGuests: 3,
        bedrooms: 0,
        bathrooms: 0,
        maxPets: 0,
        maxAdults: 2,
        maxInfants: 0,
        maxChildren: 0,
        amenities: [],
        images: [
          'https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_487/at%2Fhouse%20tours%2F2023-House-Tours%2F2023-October%2Fmiranda-co%2Ftours-brooklyn-miranda-co-6',
          'https://www.thespruce.com/thmb/OP8L0Mw0GhyPaGpEYATpJf8apTE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/bedroom-in-a-studio-apartment-4158707-hero-773f7589311c40cb9546c836abd715e2.jpg',
          'https://www.thespruce.com/thmb/lCAaC0gm0KJJTguhmHXj3hn0lj0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Cut-a-Rug-Studio-Apartment-58792dbd5f9b584db331c8dc.jpg',
        ],
        minCancelDays: 3,
        currentStep: 2,
        visitedSteps: [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 8],
      },
    ],
    skipDuplicates: true,
  });
}

main().catch(console.error).finally(disconnect);
