import 'dotenv/config';
import { createPrismaClient } from './prisma.factory';

const { prisma, disconnect } = createPrismaClient();

async function main() {
  await prisma.profile.createMany({
    data: [
      {
        supabaseId: '4f98e0ef-9c23-4ba1-9876-52e84d9f23e9',

        firstName: 'George',
        lastName: 'Washingtong',
        avatarUrl:
          'https://j1l1utk0xl.ufs.sh/f/8xgIemAiVMedMNct8OzOLKTSUlBJwgCxvENy3W2mpVHjAb8D',
        role: 'USER',
        bio: "I'm just a regular man",
      },
      {
        supabaseId: '8838d609-5b05-4a9e-80b0-0f972757606f',
        firstName: 'Staybnb',
        lastName: 'Admin',
        avatarUrl:
          'https://j1l1utk0xl.ufs.sh/f/8xgIemAiVMedCP7RVhNxytbsog2aqYN9K3crSeO6iEkhPmwZ',
        role: 'USER',
        bio: 'I am just a regular admin',
      },
      {
        supabaseId: '967c1273-d1e3-4019-ad72-39b4770ae80a',
        firstName: 'Jordan',
        lastName: 'Stanton',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/211.jpg',
        role: 'USER',
        bio: 'Fitness lover who recommends the best local trails and gyms.',
      },
      {
        supabaseId: '4f0fb227-601c-4158-a367-cc5847c8ed53',
        firstName: 'Bob',
        lastName: 'Keeling',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/169.jpg',
        role: 'USER',
        bio: null,
      },
      {
        supabaseId: '36643011-23e2-4378-99a1-b7998a66fb18',
        firstName: 'Louis',
        lastName: 'Hamill',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/197.jpg',
        role: 'USER',
        bio: 'Long-time resident of San Francisco who loves helping visitors discover hidden gems.',
      },
      {
        supabaseId: '6a0739b7-44d3-4a0b-a6d4-c3886b9bc709',
        firstName: 'Ronnie',
        lastName: 'Little',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/196.jpg',
        role: 'USER',
        bio: 'Craft enthusiast who enjoys decorating spaces with handmade touches.',
      },
      {
        supabaseId: '812bd34c-a0a5-479e-9e96-d1539cea01ee',
        firstName: 'Lowell',
        lastName: 'Spinka',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/218.jpg',
        role: 'USER',
        bio: 'Weekend adventurer who knows all the must-see spots in Houston.',
      },
      {
        supabaseId: 'a32c8c05-748b-45ac-9458-814d1be86c87',
        firstName: 'Alberto',
        lastName: 'Lynch',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/195.jpg',
        role: 'USER',
        bio: 'Cycling advocate who helps guests explore on two wheels.',
      },
      {
        supabaseId: '37896486-6eca-42fb-b070-4b9adce8b68b',
        firstName: 'Rufus',
        lastName: 'Baumbach',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/177.jpg',
        role: 'USER',
        bio: 'Language lover eager to practice and share cultural exchange.',
      },
      {
        supabaseId: '6d3bb136-781d-4481-90c5-79c15cd273ab',
        firstName: 'Charlie',
        lastName: 'Fisher',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/210.jpg',
        role: 'USER',
        bio: 'Artisan market regular who points guests to unique local crafts.',
      },
      {
        supabaseId: 'b74389e9-6e57-4c23-8aba-e606ebc64bad',
        firstName: 'Karl',
        lastName: 'Howe',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/185.jpg',
        role: 'USER',
        bio: null,
      },
      {
        supabaseId: 'e71c6967-bd15-4f34-a47f-b369349e93e3',
        firstName: 'Johnnie',
        lastName: 'Yundt',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/168.jpg',
        role: 'USER',
        bio: 'Coffee aficionado who loves sharing the best local cafés.',
      },
      {
        supabaseId: 'd744fe42-f85f-4b8f-a8b2-1a4b109def31',
        firstName: 'Regina',
        lastName: 'Renner',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/207.jpg',
        role: 'USER',
        bio: 'Eco-conscious host committed to sustainable and green hospitality.',
      },
      {
        supabaseId: '74c91ced-c02c-462b-8821-020c1996009c',
        firstName: 'Laura',
        lastName: 'Gulgowski',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/221.jpg',
        role: 'USER',
        bio: 'Adventure seeker who believes great accommodations make great trips.',
      },
      {
        supabaseId: '1e4beefb-78a3-48a9-8696-68ebeb357800',
        firstName: 'Ever',
        lastName: 'Tusan',
        avatarUrl:
          'https://j1l1utk0xl.ufs.sh/f/8xgIemAiVMeddwzCVXkQfXotIx4ZqHkjgmSBe2EbA6yhRWsC',
        role: 'ADMIN',
        bio: 'I wont tell about myself',
      },
      {
        supabaseId: 'a9173a38-4c34-4513-a94f-d2ea42a163ac',
        firstName: 'Paula',
        lastName: 'Haag',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/206.jpg',
        role: 'USER',
        bio: "Nightlife connoisseur who guides guests through Miami's vibrant scenes.",
      },
      {
        supabaseId: 'e5778d91-cd83-4baa-aa1b-5b6eb4c3722c',
        firstName: 'Leona',
        lastName: 'McCullough',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/167.jpg',
        role: 'USER',
        bio: 'Wellness advocate who offers tips for relaxation and self-care.',
      },
      {
        supabaseId: '6656ad2e-ce3c-493f-8868-7e1f0f9910d9',
        firstName: 'Suzanne',
        lastName: 'Bode',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/216.jpg',
        role: 'USER',
        bio: 'Yoga practitioner who creates peaceful and relaxing guest environments.',
      },
      {
        supabaseId: '4b38577b-babc-4cb4-babe-07d5067deacc',
        firstName: 'Regina',
        lastName: 'Lubowitz',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/202.jpg',
        role: 'USER',
        bio: 'Local host passionate about showing guests the best of Chicago.',
      },
      {
        supabaseId: 'd1a8a8cc-665f-4978-b2d6-01e68a6e4225',
        firstName: 'Nichole',
        lastName: 'Cartwright',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/204.jpg',
        role: 'USER',
        bio: 'Chef at heart who shares favorite recipes and cooking tips.',
      },
      {
        supabaseId: '42029a50-c3f2-4675-b200-1b7bf51b30b6',
        firstName: 'Ann',
        lastName: 'Leannon',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/212.jpg',
        role: 'USER',
        bio: 'Music fan who curates playlists to enhance your stay experience.',
      },
      {
        supabaseId: '67237730-69a1-4e8a-92ef-d0419eec252e',
        firstName: 'Willie',
        lastName: 'Von',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/220.jpg',
        role: 'USER',
        bio: 'Design lover who enjoys creating comfortable and stylish spaces for guests.',
      },
      {
        supabaseId: 'f3c6ebbc-2158-439a-81be-97f481ffb5f2',
        firstName: 'Dora',
        lastName: 'Tremblay',
        avatarUrl: 'https://mockmind-api.uifaces.co/content/human/219.jpg',
        role: 'USER',
        bio: 'Beach lover who knows the best hidden coastal spots.',
      },
      {
        supabaseId: 'a68951db-9701-456d-bc95-677115db809f',
        firstName: 'Pablo',
        lastName: 'Barberp222',
        avatarUrl: '',
        role: 'USER',
        bio: '222',
      },
    ],
    skipDuplicates: true,
  });
}

main().catch(console.error).finally(disconnect);
